# =========================
# Server Configuration
# =========================
server.port=8080

# =========================
# CORS (frontend origin)
# =========================
app.cors.allowed-origins=http://localhost:5000,http://127.0.0.1:5000

# =========================
# Database Configuration
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=password

# =========================
# JPA Configuration
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


##
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.connection-timeout=30000
